name: monthly-paycheck-saas
region: nyc

services:
  # FastAPI Backend - Web Service ($5/month)
  - name: backend
    source_dir: /app
    github:
      repo: YOUR_GITHUB_USERNAME/monthly-paycheck-saas
      branch: main
      deploy_on_push: true
    
    # Python environment
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # Build and run configuration
    build_command: pip install -r requirements.txt
    run_command: gunicorn -c gunicorn.conf.py main:app
    
    # HTTP configuration
    http_port: 8000
    routes:
      - path: /api
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables (set these in App Platform dashboard)
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: PYTHONPATH
        value: /app
      # Add your secrets in the App Platform dashboard:
      # JWT_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, 
      # OPENROUTER_API_KEY, MAILGUN_API_KEY, MAILGUN_DOMAIN, etc.

  # React Frontend - Static Site (FREE)
  - name: frontend
    source_dir: /frontend
    github:
      repo: YOUR_GITHUB_USERNAME/monthly-paycheck-saas
      branch: main
      deploy_on_push: true
    
    # Node.js environment
    environment_slug: node-js
    
    # Build configuration
    build_command: npm install && npm run build
    output_dir: /dist
    
    # Static site configuration
    static_sites:
      - name: frontend
        source_dir: dist
        index_document: index.html
        catchall_document: index.html  # For React Router SPA
        
    # Routes (catch-all for frontend)
    routes:
      - path: /

# No persistent storage needed - security first approach
# Company configs stored in browser localStorage
# All file processing is ephemeral and deleted immediately

# Optional: Managed database for future scaling
# databases:
#   - name: postgres
#     engine: PG
#     version: "14"
#     size: db-s-dev-database  # $7/month
