# Modern docker-compose (no version needed)

services:
  backend-test:
    build:
      context: ..
      dockerfile: config/Dockerfile.test
    container_name: monthly-paycheck-test
    # Pass environment variables from a .env file at the root of the project
    env_file:
      - ../.env
    # The command to run the tests.
    # This overrides the CMD in the Dockerfile for clarity.
    command: pytest -v -rs -s tests/

  # Main app for testing after validation
  app:
    build:
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
    profiles:
      - app 