# Modern docker-compose (no version needed)

services:
  app:
    build:
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../uploads:/app/uploads
      - ../.env:/app/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Add Redis for future RQ worker support
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data: 