# Modern docker-compose (no version needed)

services:
  test:
    build:
      context: ..
      dockerfile: config/Dockerfile.test
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app

  # Main app for testing after validation
  app:
    build:
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
    profiles:
      - app 